name: Docker Build

on:
    workflow_dispatch:

jobs:
    docker-build:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Checkout
              uses: actions/checkout@v3

            - name: Log in to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Calculate docker image tag
              id: set-tag
              uses: docker/metadata-action@master
              with:
                images: ${{ secrets.DOCKERHUB_USERNAME }}/maubot
                flavor: latest=true
#              latest=${{ github.ref == 'refs/heads/main' }}
                tags: |
                    type=pep440,pattern={{raw}}
                    type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}

            - name: Build and push to repo
              uses: docker/build-push-action@v3
              with:
                push: true
                context: .
                labels: |
                  "${{ steps.set-tag.outputs.labels }}"
                  "gitsha1=${{ github.sha }}"
                tags: "${{ steps.set-tag.outputs.tags }}"
                file: "./Dockerfile"
                platforms: linux/amd64
